Reservation/inquire/urls.py
from django.urls import path, re_path
from . import views

app_name = "inquire"
urlpatterns = [
    path("", views.inquire_view, name="inquire"),
    re_path(r'^modify/$', views.inquire_modify_view, name="inquire_modify"),
    re_path(r'^delete/$', views.inquire_delete_view, name="inquire_delete")
]

Reservation/login/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path("", views.login_view, name="login"),
    path("logout/", views.logout_user, name="logout_user"),
    path("login/", views.select_view, name="afterLogin"),
]

Reservation/restaurant/urls.py
from django.urls import path, re_path
from . import views

app_name = "restaurant"
urlpatterns = [
    path("", views.restaurant_view, name="restaurant"),
    re_path(r'^reservation/$', views.restaurant_reservation_view, name="restaurant_reservation")
]

Reservation/restaurantInquire/urls.py
from django.urls import path, re_path
from . import views

app_name = "restaurantInquire"
urlpatterns = [
    path("", views.rinquire_view, name="rinquire"),
    re_path(r'^modify/$', views.rinquire_modify_view, name="rinquire_modify"),
    re_path(r'^delete/$', views.rinquire_delete_view, name="rinquire_delete")
]

Reservation/room/urls.py
from django.urls import path, re_path
from . import views

app_name = "room"
urlpatterns = [
    path("", views.room_view, name="room"),
    re_path(r'^reservation/$', views.room_reservation_view, name="room_reservation")
]

Reservation/inquire/models.py
from django.db import models

# Create your models here.

Reservation/login/models.py
from django.db import models

# Create your models here.

Reservation/restaurant/models.py
from django.db import models

# Create your models here.

Reservation/restaurantInquire/models.py
from django.db import models

# Create your models here.

Reservation/room/models.py
from django.db import models

# Create your models here.

Reservation/inquire/views.py
import requests
from django.conf import settings
from django.template.loader import get_template
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


# Create your views here.

def inquire_view(request):
    # reservation_url = 'http://127.0.0.1:8080/api/room/inquire'
    reservation_url = settings.ROOM_BACKEND + '/api/room/inquire'
    reservation_result = requests.get(reservation_url).json()

    for i in range(len(reservation_result)):
        roomId = reservation_result[i]["RoomId"]
        # room_url = 'http://127.0.0.1:8080/api/room/roomId/'+roomId
        room_url = settings.ROOM_BACKEND + '/api/room/roomId/' + roomId
        room_result = requests.get(room_url).json()
        reservation_result[i]["RoomId"] = room_result["RoomName"]
    
    context = {
        'reservations': reservation_result,
    }

    return render(request, "inquire.html", context)

def inquire_modify_view(request):
    if request.method == "GET":
        reservationId = request.GET.get('Id')
        # reservation_url = 'http://127.0.0.1:8080/api/room/inquire/'+reservationId
        reservation_url = settings.ROOM_BACKEND + '/api/room/inquire/'+reservationId
        reservation_result = requests.get(reservation_url).json()
        rdate = reservation_result["Rdate"]
        rtime = reservation_result["Rtime"]
        rname = reservation_result["Rname"]
        rpeople = reservation_result["Rpeople"]
        rtitle = reservation_result["Rtitle"]
        rdetail = reservation_result["Rdetail"]
        roomId = reservation_result["RoomId"]
        # room_url = 'http://127.0.0.1:8080/api/room/roomId/'+roomId
        room_url = settings.ROOM_BACKEND + '/api/room/roomId/'+roomId
        room_result = requests.get(room_url).json()
        roomName = room_result["RoomName"]

        context = {
            'ReservationId' : reservationId,
            'date':rdate,
            'time':rtime,
            'name':rname,
            'people':rpeople,
            'title':rtitle,
            'detail':rdetail,
            'room':roomName
    }
        return render(request, "inquireModify.html", context)

    else:
        reservationId = request.GET.get('Id')
        # reservation_url = 'http://127.0.0.1:8080/api/room/inquire/'+reservationId
        reservation_url = settings.ROOM_BACKEND + '/api/room/inquire/'+reservationId
        reservation_result = requests.get(reservation_url).json()
        rId = reservation_result["ReservationId"]
        room = reservation_result["RoomId"]
        date = reservation_result["Rdate"]
        time = reservation_result["Rtime"]

        name = request.POST.get('inquireMname')
        people = request.POST.get('inquireMpeople')
        title = request.POST.get('inquireMtitle')
        detail = request.POST.get('inquireMdetail')

        data = {
            'ReservationId' : rId,
            'RoomId' : room,
            'Rdate' : date,
            'Rtime' : time,
            'Rname' : name,
            'Rpeople' : people,
            'Rtitle' : title,
            'Rdetail' : detail
        }

        result = requests.put(reservation_url, data)

        return HttpResponseRedirect(reverse("inquire:inquire"))

def inquire_delete_view(request):
    if request.method == "GET":
        reservationId = request.GET.get('Id')
        # reservation_url = 'http://127.0.0.1:8080/api/room/inquire/'+reservationId
        reservation_url = settings.ROOM_BACKEND + '/api/room/inquire/'+reservationId

        result = requests.delete(reservation_url)

        return HttpResponseRedirect(reverse("inquire:inquire"))

    

Reservation/login/views.py
from django.template.loader import get_template
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate

# Create your views here.
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse("login:login"))

def login_view(request):
    if request.method == "GET":
        context = {
            'user': "",
            'error_text': ""
        }
        return render(request, "login.html", context)
    else:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            return HttpResponseRedirect(reverse("login:afterLogin"))
        else:
            context = {
                'user': username,
                'error_text': "Login Fail!"
            }
            return render(request, "login.html", context)

def select_view(request):
    return render(request, "afterLogin.html")

Reservation/restaurant/views.py
from django.http.response import JsonResponse
import requests
from django.conf import settings
from django.template.loader import get_template
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from datetime import datetime
from django.urls import reverse

# Create your views here.

def restaurant_view(request):
    # restaurant_url = 'http://127.0.0.1:8081/api/restaurant/restaurant'
    restaurant_url = settings.RESTAURANT_BACKEND + '/api/restaurant/restaurant'
    restaurant_result = requests.get(restaurant_url)

    # chain_url = 'http://127.0.0.1:8081/api/restaurant/chain'
    chain_url = settings.RESTAURANT_BACKEND + '/api/restaurant/chain'
    chain_result = requests.get(chain_url)

    # time_url = 'http://127.0.0.1:8081/api/restaurant/time'
    time_url = settings.RESTAURANT_BACKEND + '/api/restaurant/time'
    time_result = requests.get(time_url)

    if request.GET.get('restaurantdate')!='':
        date = request.GET.get('restaurantdate')

    context = {
        'restaurants': restaurant_result.json(),
        'chains': chain_result.json(),
        'times': time_result.json(),
        'date' : date
    }

    return render(request, "restaurant.html", context)
    
def restaurant_reservation_view(request):
    if request.method == "GET":
        chain = request.GET.get('chain')

        # chain_url = 'http://127.0.0.1:8081/api/restaurant/chainName/'+chain
        chain_url = settings.RESTAURANT_BACKEND + '/api/restaurant/chainName/'+chain
        chain_result = requests.get(chain_url).json()
        chainopentime = chain_result["ChainOpenTime"]
        time = request.GET.get('time')
        date = request.GET.get('date')

        context = {
            'chain':chain,
            'opentime':chainopentime,
            'date':date,
            'time':time
        }
        return render(request, "restaurantReservation.html", context)

    else:
        # reservation_url = 'http://127.0.0.1:8081/api/restaurant/inquire'
        reservation_url = settings.RESTAURANT_BACKEND + '/api/restaurant/inquire'

        time = request.GET.get('time')
        chain = request.GET.get('chain')
        # chain_url = 'http://127.0.0.1:8081/api/restaurant/chainName/'+chain
        chain_url = settings.RESTAURANT_BACKEND + '/api/restaurant/chainName/'+chain
        chain_result = requests.get(chain_url).json()
        chainId = chain_result["ChainId"]

        date = request.GET.get('date')
        name = request.POST.get('restaurantRname')
        people = request.POST.get('restaurantRpeople')
        detail = request.POST.get('restaurantRdetail')

        data = {
            'ChainId' : chainId,
            'Rdate' : date,
            'Rtime' : time,
            'Rname' : name,
            'Rpeople' : people,
            'Rdetail' : detail
        }

        result = requests.post(reservation_url, data)

        return HttpResponseRedirect(reverse("restaurant:restaurant"))

Reservation/restaurantInquire/views.py
import requests
from django.conf import settings
from django.template.loader import get_template
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


# Create your views here.

def rinquire_view(request):
    # reservation_url = 'http://127.0.0.1:8081/api/restaurant/inquire'
    reservation_url = settings.RESTAURANT_BACKEND + '/api/restaurant/inquire'
    reservation_result = requests.get(reservation_url).json()

    for i in range(len(reservation_result)):
        chainId = reservation_result[i]["ChainId"]
        # chain_url = 'http://127.0.0.1:8081/api/restaurant/chainId/'+ chainId
        chain_url = settings.RESTAURANT_BACKEND + '/api/restaurant/chainId/'+ chainId
        chain_result = requests.get(chain_url).json()
        reservation_result[i]["ChainId"] = chain_result["ChainName"]
    
    context = {
        'reservations': reservation_result,
    }

    return render(request, "restaurantInquire.html", context)

def rinquire_modify_view(request):
    if request.method == "GET":
        reservationId = request.GET.get('Id')
        # reservation_url = 'http://127.0.0.1:8081/api/restaurant/inquire/'+reservationId
        reservation_url = settings.RESTAURANT_BACKEND + '/api/restaurant/inquire/'+reservationId
        reservation_result = requests.get(reservation_url).json()
        rdate = reservation_result["Rdate"]
        rtime = reservation_result["Rtime"]
        rname = reservation_result["Rname"]
        rpeople = reservation_result["Rpeople"]
        rdetail = reservation_result["Rdetail"]
        chainId = reservation_result["ChainId"]
        # chain_url = 'http://127.0.0.1:8081/api/restaurant/chainId/'+chainId
        chain_url = settings.RESTAURANT_BACKEND + '/api/restaurant/chainId/'+chainId
        chain_result = requests.get(chain_url).json()
        chainName = chain_result["ChainName"]

        context = {
            'ReservationId' : reservationId,
            'date':rdate,
            'time':rtime,
            'name':rname,
            'people':rpeople,
            'detail':rdetail,
            'chain':chainName
    }
        return render(request, "restaurantInquireModify.html", context)

    else:
        reservationId = request.GET.get('Id')
        # reservation_url = 'http://127.0.0.1:8081/api/restaurant/inquire/'+reservationId
        reservation_url = settings.RESTAURANT_BACKEND + '/api/restaurant/inquire/'+reservationId
        reservation_result = requests.get(reservation_url).json()
        rId = reservation_result["ReservationId"]
        chain = reservation_result["ChainId"]
        date = reservation_result["Rdate"]
        time = reservation_result["Rtime"]

        name = request.POST.get('inquireMname')
        people = request.POST.get('inquireMpeople')
        detail = request.POST.get('inquireMdetail')

        data = {
            'ReservationId' : rId,
            'RoomId' : chain,
            'Rdate' : date,
            'Rtime' : time,
            'Rname' : name,
            'Rpeople' : people,
            'Rdetail' : detail
        }

        result = requests.put(reservation_url, data)

        return HttpResponseRedirect(reverse("restaurantInquire:rinquire"))

def rinquire_delete_view(request):
    if request.method == "GET":
        reservationId = request.GET.get('Id')
        # reservation_url = 'http://127.0.0.1:8081/api/restaurant/inquire/'+reservationId
        reservation_url = settings.RESTAURANT_BACKEND + '/api/restaurant/inquire/'+reservationId

        result = requests.delete(reservation_url)

        return HttpResponseRedirect(reverse("restaurantInquire:rinquire"))

    

Reservation/room/views.py
from django.http.response import JsonResponse
import requests
from django.conf import settings
from django.template.loader import get_template
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from datetime import datetime
from django.urls import reverse

# Create your views here.

def room_view(request):
    # company_url = 'http://127.0.0.1:8080/api/room/company'
    company_url = settings.ROOM_BACKEND + '/api/room/company'
    company_result = requests.get(company_url)

    # room_url = 'http://127.0.0.1:8080/api/room/room'
    room_url = settings.ROOM_BACKEND + '/api/room/room'
    room_result = requests.get(room_url)

    # time_url = 'http://127.0.0.1:8080/api/room/time'
    time_url = settings.ROOM_BACKEND + '/api/room/time'
    time_result = requests.get(time_url)

    if request.GET.get('roomdate')!='':
        date = request.GET.get('roomdate')

    context = {
        'companies': company_result.json(),
        'rooms': room_result.json(),
        'times': time_result.json(),
        'date' : date
    }

    return render(request, "room.html", context)
    
def room_reservation_view(request):
    if request.method == "GET":
        room = request.GET.get('room')
        time = request.GET.get('time')
        date = request.GET.get('date')
        context = {
            'room':room,
            'date':date,
            'time':time
        }
        return render(request, "roomReservation.html", context)

    else:
        # reservation_url = 'http://127.0.0.1:8080/api/room/inquire'
        reservation_url = settings.ROOM_BACKEND + '/api/room/inquire'

        time = request.GET.get('time')
        room = request.GET.get('room')
        # room_url = 'http://127.0.0.1:8080/api/room/roomName/'+room
        room_url = settings.ROOM_BACKEND + '/api/room/roomName/'+room
        room_result = requests.get(room_url).json()
        roomId = room_result["RoomId"]

        date = request.GET.get('date')
        name = request.POST.get('roomRname')
        people = request.POST.get('roomRpeople')
        title = request.POST.get('roomRtitle')
        detail = request.POST.get('roomRdetail')

        data = {
            'RoomId' : roomId,
            'Rdate' : date,
            'Rtime' : time,
            'Rname' : name,
            'Rpeople' : people,
            'Rtitle' : title,
            'Rdetail' : detail
        }

        result = requests.post(reservation_url, data)

        return HttpResponseRedirect(reverse("room:room"))

Reservation/templates/base.html
<!--base.html-->
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Reservation</title>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        {% block ref %}
        {% endblock %}

    </head>
    {% block content %}
        {% block js-ref %}
        {% endblock js-ref %}
    {% endblock content %}
</html>

Reservation/templates/inquire.html
{% extends "base.html" %}
{% load static %}

{% block ref %}
<link rel="stylesheet" href="{% static 'css/inquire/inquire.css' %}">
{% endblock %}

{% block content %}
<nav>
    <div class="nav-wrapper grey darken-1 inquirenav">
      <a href="{% url 'login:afterLogin' %}" class="logo">R</a>
      <span class="navtitle">預約系統</span>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="{% url 'login:logout_user' %}" class="navlink">登出</a></li>
      </ul>
    </div>
</nav>
<div class="row inquiretitle">
    <h3>預約查詢</h3>        
</div>
<body> 
    <div class="sidenav sidenav-fixed grey inquiresidenav">
        <ul id="slide-out">
            <li><a href="{% url 'room:room' %}" class="navsidelink">場地預約</a></li>
            <li><a href="{% url 'inquire:inquire' %}" class="navsidelink">預約查詢</a></li>
            <li><a href="{% url 'restaurant:restaurant' %}" class="navsidelink">餐廳訂位</a></li>
            <li><a href="{% url 'restaurantInquire:rinquire' %}" class="navsidelink">訂位查詢</a></li>
        </ul>
    </div>
    
    <div class="inquirepage">
        <div class="row">
            <form method="POST">
                <table class="striped col s12">
                    <thead>
                        <tr>
                            <th width="10%">場地</th>
                            <th width="10%">日期</th>
                            <th width="10%">時間</th>
                            <th width="10%">預約姓名</th>
                            <th width="10%">人數</th>
                            <th width="10%">主題</th>
                        </tr>
                    </thead>

                    {% for reservation in reservations %}
                    <tbody>
                        <tr>
                            <td><a href="{% url 'inquire:inquire_modify' %}?Id={{ reservation.ReservationId }}"> {{ reservation.RoomId }}</a></td>
                            <td>{{ reservation.Rdate }}</td>
                            <td>{{ reservation.Rtime }}</td>
                            <td>{{ reservation.Rname }}</td>
                            <td>{{ reservation.Rpeople }}</td>
                            <td>{{ reservation.Rtitle }}</td>
                        </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </form>    
        </div>     
    </div>
    

{% block js-ref %}
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript", src="{% static 'js/materialize.js' %}"></script> 
{% endblock js-ref %}

</body>
{% endblock content %}

Reservation/templates/inquireModify.html
{% extends "base.html" %}
{% load static %}

{% block ref %}
<link rel="stylesheet" href="{% static 'css/inquire/inquireModify.css' %}">
{% endblock %}

{% block content %}
<nav>
    <div class="nav-wrapper grey darken-1 inquirenav">
      <a href="{% url 'login:afterLogin' %}" class="logo">R</a>
      <span class="navtitle">預約系統</span>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="{% url 'login:logout_user' %}" class="navlink">登出</a></li>
      </ul>
    </div>
</nav>
<div class="row inquiretitle">
    <h3>預約修改 - {{ room }}</h3>        
</div>
<body> 
    <div class="sidenav sidenav-fixed grey inquiresidenav">
        <ul id="slide-out">
            <li><a href="{% url 'room:room' %}" class="navsidelink">場地預約</a></li>
            <li><a href="{% url 'inquire:inquire' %}" class="navsidelink">預約查詢</a></li>
            <li><a href="{% url 'restaurant:restaurant' %}" class="navsidelink">餐廳訂位</a></li>
            <li><a href="{% url 'restaurantInquire:rinquire' %}" class="navsidelink">訂位查詢</a></li>
        </ul>
    </div>
    
    <div class="inquirepage">
        <form class="col" method="POST">
            {% csrf_token %}
            <div class="row inquireMform">
                <div class="input-field col s6">
                    <input disabled value={{date}} type="text" id="inquireMdate" name="inquireMdate" required>
                    <label for="inquireMdate">日期</label>
                </div>
            </div>
            <div class="row inquireMform">
                <div class="input-field col s6">
                    <input disabled value={{time}} type="text" id="inquireMtime" name="inquireMtime" required>
                    <label for="inquireMtime">時間</label>
                </div>
            </div>
            <div class="row inquireMform">
                <div class="input-field col s6">
                    <input value={{name}} type="text" id="inquireMname" name="inquireMname" required>
                    <label for="inquireMname">姓名</label>
                </div>
            </div>
            <div class="row inquireMform">
                <div class="input-field col s6">
                    <input value={{people}} type="text" id="inquireMpeople" name="inquireMpeople" required>
                    <label for="inquireMpeople">人數</label>
                </div>
            </div>
            <div class="row inquireMform">
                <div class="input-field col s6">
                    <input value={{title}} type="text" id="inquireMtitle" name="inquireMtitle">
                    <label for="inquireRtitle">主題</label>
                </div>
            </div>
            <div class="row inquireMform">
                <div class="input-field col s6">
                    <input value={{detail}} type="text" id="inquireMdetail" name="inquireMdetail">
                    <label for="inquireMdetail">備註</label>
                </div>
            </div>
            <div class="row">
                <button class="btn waves-effect waves-white right grey inquireMbtn"><a href="{% url 'inquire:inquire_delete' %}?Id={{ ReservationId }}" class="white-text">刪除預約</a>
                    <i class="material-icons right"><a href="{% url 'inquire:inquire_delete' %}?Id={{ ReservationId }}" class="white-text">delete</a></i>
                </button>
                <button class="btn waves-effect waves-white right grey inquireMbtn"><a href="{% url 'inquire:inquire' %}" class="white-text">取消修改</a>
                    <i class="material-icons right"><a href="{% url 'inquire:inquire' %}" class="white-text">clear</a></i>
                </button>
                <button class="btn waves-effect waves-white right grey inquireMbtn" type="submit">確認修改
                    <i class="material-icons right">check</i>
                </button>
            </div>    
        </form>       
    </div>
    

{% block js-ref %}
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript", src="{% static 'js/materialize.js' %}"></script> 
{% endblock js-ref %}

</body>
{% endblock content %}

Reservation/templates/restaurant.html
{% extends "base.html" %}
{% load static %}

{% block ref %}
<link rel="stylesheet" href="{% static 'css/restaurant/restaurant.css' %}">
{% endblock %}

{% block content %}
<nav>
    <div class="nav-wrapper grey darken-1 restaurantnav">
      <a href="{% url 'login:afterLogin' %}" class="logo">R</a>
      <span class="navtitle">預約系統</span>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="{% url 'login:logout_user' %}" class="navlink">登出</a></li>
      </ul>
    </div>
</nav>
<div class="row restauranttitle">
    <h3>餐廳訂位</h3>        
</div>
<body> 
    <div class="sidenav sidenav-fixed grey restaurantsidenav">
        <ul id="slide-out">
            <li><a href="{% url 'room:room' %}" class="navsidelink">場地預約</a></li>
            <li><a href="{% url 'inquire:inquire' %}" class="navsidelink">預約查詢</a></li>
            <li><a href="{% url 'restaurant:restaurant' %}" class="navsidelink">餐廳訂位</a></li>
            <li><a href="{% url 'restaurantInquire:rinquire' %}" class="navsidelink">訂位查詢</a></li>
        </ul>
    </div>
    
    <div class="restaurantpage">
        {% for restaurant in restaurants %}
        <div class="row">
            <h4>{{ restaurant.RestaurantName }}</h4>  
        </div>
        {% endfor %}

        <div class="row">
            <form method=" ">
                <div class="col s6">
                    <div class="input-field col s6">
                        <input type=text id="restaurantdate" class="datepicker" name="restaurantdate" value={{date}} required>
                        <label for="restaurantdate">日期</label>
                    </div>
                    <div class="col s1">
                        <button class="btn grey" type="submit"><i class="material-icons">check</i></button>
                    </div>
                </div>
                <table class="striped col s12">
                    {% for time in times %}
                    <thead>
                        <tr>
                            <th></th>
                            <th>{{ time.Time1 }}</th>
                            <th>{{ time.Time2 }}</th>
                            <th>{{ time.Time3 }}</th>
                            <th>{{ time.Time4 }}</th>
                            <th>{{ time.Time5 }}</th>
                        </tr>
                    </thead>
                    
                    {% for chain in chains %}
                    <tbody>
                        <tr>
                            <td>{{ chain.ChainName }}</td>
                            <td><a href="{% url 'restaurant:restaurant_reservation' %}?chain={{ chain.ChainName }}&date={{ date }}&time={{ time.Time1 }}">Available</a></td>
                            <td><a href="{% url 'restaurant:restaurant_reservation' %}?chain={{ chain.ChainName }}&date={{ date }}&time={{ time.Time2 }}">Available</a></td>
                            <td><a href="{% url 'restaurant:restaurant_reservation' %}?chain={{ chain.ChainName }}&date={{ date }}&time={{ time.Time3 }}">Available</a></td>
                            <td><a href="{% url 'restaurant:restaurant_reservation' %}?chain={{ chain.ChainName }}&date={{ date }}&time={{ time.Time4 }}">Available</a></td>
                            <td><a href="{% url 'restaurant:restaurant_reservation' %}?chain={{ chain.ChainName }}&date={{ date }}&time={{ time.Time5 }}">Available</a></td>
                        </tr>
                    </tbody>
                    {% endfor %}
                    {% endfor %}
                </table>
            </form>    
        </div>     
    </div>
    

{% block js-ref %}
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript", src="{% static 'js/materialize.js' %}"></script> 
<script type="text/javascript", src="{% static 'js/restaurant/restaurant.js' %}"></script>
{% endblock js-ref %}

</body>
{% endblock content %}

Reservation/templates/restaurantInquire.html
{% extends "base.html" %}
{% load static %}

{% block ref %}
<link rel="stylesheet" href="{% static 'css/restaurantInquire/restaurantInquire.css' %}">
{% endblock %}

{% block content %}
<nav>
    <div class="nav-wrapper grey darken-1 rinquirenav">
      <a href="{% url 'login:afterLogin' %}" class="logo">R</a>
      <span class="navtitle">預約系統</span>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="{% url 'login:logout_user' %}" class="navlink">登出</a></li>
      </ul>
    </div>
</nav>
<div class="row rinquiretitle">
    <h3>訂位查詢</h3>        
</div>
<body> 
    <div class="sidenav sidenav-fixed grey rinquiresidenav">
        <ul id="slide-out">
            <li><a href="{% url 'room:room' %}" class="navsidelink">場地預約</a></li>
            <li><a href="{% url 'inquire:inquire' %}" class="navsidelink">預約查詢</a></li>
            <li><a href="{% url 'restaurant:restaurant' %}" class="navsidelink">餐廳訂位</a></li>
            <li><a href="{% url 'restaurantInquire:rinquire' %}" class="navsidelink">訂位查詢</a></li>
        </ul>
    </div>
    
    <div class="rinquirepage">
        <div class="row">
            <form method="POST">
                <table class="striped col s12">
                    <thead>
                        <tr>
                            <th width="10%">場地</th>
                            <th width="10%">日期</th>
                            <th width="10%">時間</th>
                            <th width="10%">預約姓名</th>
                            <th width="10%">人數</th>
                        </tr>
                    </thead>

                    {% for reservation in reservations %}
                    <tbody>
                        <tr>
                            <td><a href="{% url 'restaurantInquire:rinquire_modify' %}?Id={{ reservation.ReservationId }}"> {{ reservation.ChainId }}</a></td>
                            <td>{{ reservation.Rdate }}</td>
                            <td>{{ reservation.Rtime }}</td>
                            <td>{{ reservation.Rname }}</td>
                            <td>{{ reservation.Rpeople }}</td>
                        </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </form>    
        </div>     
    </div>
    

{% block js-ref %}
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript", src="{% static 'js/materialize.js' %}"></script> 
{% endblock js-ref %}

</body>
{% endblock content %}